spring:
  boot:
    admin:
      username: admin       #These two are needed so that the client
      password: pass   #can register at the protected server api
  zipkin:
    base-url: http://zipkin.orrin.com:8763

  datasource:
    druid:
      url: jdbc:mysql://mysql.orrin.com:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000

# Disable spring basic authentication security
security:
  oauth2:
#    sso:
#      login-path: /login
    client:
      client-id: acme
      client-secret: acmesecret
      access-token-uri: http://uaa.orrin.com:8769/oauth/token
      user-authorization-uri: http://uaa.orrin.com:8769/oauth/authorize
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----
      id: openid
      serviceId: ${PREFIX:}resource

swagger2:
  docket:
    ##扫描报路径
    basepackage: com.orrin.scab.product.oauth.resource.web
    ##过滤的路径，支持正则表达式, 可以配置为 *
    paths: /*
    ##分组
    groupName:
    ##base，最终调用接口后会和paths拼接在一起, 可以配置为 /
    pathMapping: /

  apiInfo:
    ##大标题
    title: business-service-oauth-resource
    ##描述
    description: business-service-oauth-resource描述local环境
    ##
    termsOfServiceUrl: /
    ##作者
    contact_name:  Orrin
    ##链接显示文字
    contact_url: /
    ##邮件地址
    contact_email:  orrin2008@126.com
    ##版本
    version:  1.0.0
#info:
#  version: @project.version@