spring:
  application:
    name: common-service-turbine
  cloud:
    inetutils:
      preferred-networks:
        - 192.168.35
        - 127.0.0.1
  boot:
    admin:
      url: http://admin.orrin.com:7999
      username: mgmt         #These two are needed so that the client
      password: mgmt         #can register at the protected server api

# Define the port where the Service Registry server would be running
server:
  port: 8762


# Defines the Eureka server that is used by the Netflix OSS components to use as the registry
# for server discovery
eureka:
  instance:
    hostname: www.orrin.com
  client:
    serviceUrl:
      defaultZone: http://eureka.orrin.com:8761/eureka

security:
  basic:
    enabled: false
turbine:
  ### 配置Eureka中的serviceId列表，表明监控哪些服务,逗号间隔
  app-config: service-hi,service-lucy,common-service-uaa,common-service-apigateway
  instanceUrlSuffix: ${management.context-path}/hystrix.stream
  cluster-name-expression: new String("default")
  combine-host-port: true

info:
  version: @project.version@

management:
  context-path: /mgmt
  security:
    enabled: false
