spring:
  application:
    name: common-service-file
  cloud:
    inetutils:
      preferred-networks:
        - 192.168.35
        - 127.0.0.1
  boot:
    admin:
      url: http://admin.orrin.com:7999
      username: admin       #These two are needed so that the client
      password: pass   #can register at the protected server api
      client:
        metadata:
          user.name: mgmt          #These two are needed so that the server
          user.password: mgmt #can access the proteceted client endpoints

  zipkin:
    base-url: http://zipkin.orrin.com:8763

# Define the port where the Widget Foundry server would be running
server:
  port: 8064

# Define the Eureka server that handles service registration
eureka:
  instance:
    hostname: www.orrin.com
    port: 8761
  client:
    serviceUrl:
      defaultZone: http://eureka.orrin.com:${eureka.instance.port}/eureka/

# Disable spring basic authentication security
security:
  basic:
    enabled: false
  sessions: stateless
  oauth2:
    sso:
      login-path: /login
    client:
      client-id: acme
      client-secret: acmesecret
      access-token-uri: http://uaa.orrin.com:8769/oauth/token
      user-authorization-uri: http://uaa.orrin.com:8769/oauth/authorize
    resource:
      #loadBalanced: true  #设置这个才可以使用eureka的服务名，配合loadBalancerInterceptor bean。
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----
      id: openid
      serviceId: ${PREFIX:}resource
  user:
    name: mgmt
    password: mgmt

management:
  context-path: /mgmt

logging:
  level:
    org.springframework.security: DEBUG

fdfs:
  connect_timeout: 30
  network_timeout: 30
  charset: UTF-8
  http:
    tracker_http_port: 8080
    anti_steal_token: true
    secret_key: FastDFS1234567890
  tracker_server:
    - 192.168.1.187:22122