spring:
  application:
    name: common-service-zipkin
  cloud:
    inetutils:
      preferred-networks:
        - 192.168.35
        - 127.0.0.1
  boot:
    admin:
      url: http://admin.orrin.com:7999
      username: mgmt         #These two are needed so that the client
      password: mgmt         #can register at the protected server api
  #sleuth:
    #enabled: false

management:
  security:
    enabled: false
  context-path: /mgmt

# Define the port where the Service Registry server would be running
server:
  port: 8763

# Defines the Eureka server that is used by the Netflix OSS components to use as the registry
# for server discovery
eureka:
  instance:
    hostname: www.orrin.com
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka.orrin.com:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0

#zipkin:
  #storage:
    #StorageComponent: elasticsearch
    #type: elasticsearch
    #elasticsearch:
      #cluster: elasticsearch
      #hosts: mongodb.orrin.com:9301
      #max-requests: 64
      #index: zipkin
      #index-shards: 5
      #index-replicas: 1


info:
  version: @project.version@