spring:
  application:
    name: common-service-zipkin
  boot:
    admin:
      url: http://admin.orrin.com:7999
      username: mgmt         #These two are needed so that the client
      password: mgmt         #can register at the protected server api

management:
  security:
    enabled: false
  context-path: /mgmt

# Define the port where the Service Registry server would be running
server:
  port: 8763

# Defines the Eureka server that is used by the Netflix OSS components to use as the registry
# for server discovery
eureka:
  instance:
    port: 8761
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://eureka.orrin.com:8761}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0


info:
  version: @project.version@