sys_env: local
spring:
  boot:
    admin:
      url: http://admin.orrin.com:7999
      username: mgmt       #These two are needed so that the client
      password: mgmt   #can register at the protected server api
      client:
        metadata:
          user.name: mgmt          #These two are needed so that the server
          user.password: mgmt #can access the proteceted client endpoints

  redis:
    host: redis.orrin.com
    port: 6379
    database: 5

  datasource:
    druid:
      url: jdbc:log4jdbc:mysql://mysql.orrin.com:3306/spring-cloud-uaa?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
      username: root
      password: 123456
      driver-class-name: net.sf.log4jdbc.DriverSpy
      filter:
        config:
          enabled: true
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000

logging:
  level:
    root: DEBUG
    java.sql: DEBUG
    com.orrin.: debug

# Disable spring basic authentication security
security:
  oauth2:
#    sso:
#      login-path: /login
    client:
      client-id: acme
      client-secret: acmesecret
      access-token-uri: http://uaa.orrin.com:8769/oauth/token
      user-authorization-uri: http://uaa.orrin.com:8769/oauth/authorize
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----
      id: openid
      serviceId: ${PREFIX:}resource
  user:
    name: mgmt
    password: mgmt

info:
  version: @project.version@